language: node_js
node_js:
  - 11.0.0

script:
  - npm install -g @stoplight/spectral
  - npm install -g speccy
#  - spectral lint ./api/*/*.yaml

  - |
    cd ./api
    for d in *; do
      speccy resolve $d/index.yaml > index-$d.yaml
      spectral lint index-$d.yaml
    done
